dist: xenial
language: php

php:
 - 7.2
 - 7.3

before_script:
 - LEVELDB_VERSION=f1463cb0b2486b0caf7d42ca3c7684545e875f04
 - curl -fsSL "https://github.com/pmmp/leveldb-mcpe/archive/f1463cb0b2486b0caf7d42ca3c7684545e875f04.tar.gz" | tar -zx
 - mv leveldb-mcpe-$LEVELDB_VERSION leveldb-mcpe
 - cd leveldb-mcpe && make -j4 && mv out-shared/libleveldb.* . && cd ..
 - git clone https://github.com/reeze/php-leveldb.git leveldb
 - cd leveldb
 - git checkout 9bcae79f71b81a5c3ea6f67e45ae9ae9fb2775a5
 - phpize
 - ./configure --with-leveldb=../leveldb-mcpe && make && make install
 - cd ..
 - git clone https://github.com/pmmp/ext-chunkutils2.git chunkutils
 - cd chunkutils
 - git checkout d8d762a597ac0da6f333f862096d6af0e6286b75
 - phpize
 - ./configure && make && make install
 - cd ..
# - pecl install channel://pecl.php.net/pthreads-3.1.6
 - echo | pecl install channel://pecl.php.net/yaml-2.0.4
 - pecl install channel://pecl.php.net/crypto-0.3.1
 - pecl install channel://pecl.php.net/ds-1.2.8
 - git clone https://github.com/pmmp/pthreads.git
 - cd pthreads
 - git checkout 6ca019c58b4fa09ee2ff490f2444e34bef0773d0
 - phpize
 - ./configure
 - make
 - make install
 - cd ..
 - echo "extension=pthreads.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - echo "extension=chunkutils2.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - echo "extension=leveldb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - composer install

script:
 - ./tests/travis.sh -t4

notifications:
 email: false
