language: php

php:
 - 5.4
 - 5.5
 - 5.6

branches:
  except:
    - Core-Rewrite

before_script:
 - pecl install channel://pecl.php.net/pthreads-2.0.2
 - echo | pecl install channel://pecl.php.net/yaml-1.1.1

script:
 - php src/tests/ServerSuiteTest.php --no-wizard
 
notifications:
 email: false
 webhooks: http://n.tkte.ch/h/214/wsNvmG43-ncxUVRrFPwSM-r0