language: php

php:
 - 7.2

before_script:
# - pecl install channel://pecl.php.net/pthreads-3.1.6
 - echo | pecl install channel://pecl.php.net/yaml-2.0.2
 - git clone https://github.com/pmmp/pthreads.git
 - cd pthreads
 - git checkout c8cfacda84f21032d6014b53e72bf345ac901dac
 - phpize
 - ./configure
 - make
 - make install
 - cd ..
 - echo "extension=pthreads.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - composer install

script:
 - ./tests/travis.sh -t4

notifications:
 email: false
