name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-php:
    name: Prepare PHP
    runs-on: ${{ matrix.image }}

    strategy:
      matrix:
        image: [ubuntu-20.04]
        php: [7.3.27, 7.4.15]

    steps:
      - uses: actions/checkout@v2 #needed for build.sh
      - name: Check for PHP build cache
        id: php-build-cache
        uses: actions/cache@v2
        with:
          path: "./bin"
          key: "php-build-generic-${{ matrix.php }}-${{ matrix.image }}-${{ hashFiles('./tests/gh-actions/build.sh') }}"

      - name: Compile PHP
        if: steps.php-build-cache.outputs.cache-hit != 'true'
        run: ./tests/gh-actions/build.sh "${{ matrix.php }}"

  phpstan:
    name: PHPStan analysis
    needs: build-php
    runs-on: ${{ matrix.image }}

    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu-20.04]
        php: [7.3.27, 7.4.15]

    steps:
      - uses: actions/checkout@v2

      - name: Restore PHP build cache
        id: php-build-cache
        uses: actions/cache@v2
        with:
          path: "./bin"
          key: "php-build-generic-${{ matrix.php }}-${{ matrix.image }}-${{ hashFiles('./tests/gh-actions/build.sh') }}"

      - name: Kill build on PHP build cache miss (should never happen)
        if: steps.php-build-cache.outputs.cache-hit != 'true'
        run: exit 1

      - name: Install cached PHP's dependencies
        if: steps.php-build-cache.outputs.cache-hit == 'true'
        run: chmod +x ./bin/php7/install-dependencies.sh && ./bin/php7/install-dependencies.sh

      - name: Prefix PHP to PATH
        run: echo "$(pwd)/bin/php7/bin" >> $GITHUB_PATH

      - name: Install Composer
        run: curl -sS https://getcomposer.org/installer | php

      - name: Restore Composer package cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/composer/files
            ~/.cache/composer/vcs
          key: "composer-v2-cache-${{ matrix.php }}-${{ hashFiles('./composer.lock') }}"
          restore-keys: |
            composer-v2-cache-

      - name: Install Composer dependencies
        run: php composer.phar install --prefer-dist --no-interaction

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyze --no-progress --memory-limit=2G

  phpunit:
    name: PHPUnit tests
    needs: build-php
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu-20.04]
        php: [7.3.27, 7.4.15]

    steps:
      - uses: actions/checkout@v2

      - name: Restore PHP build cache
        id: php-build-cache
        uses: actions/cache@v2
        with:
          path: "./bin"
          key: "php-build-generic-${{ matrix.php }}-${{ matrix.image }}-${{ hashFiles('./tests/gh-actions/build.sh') }}"

      - name: Kill build on PHP build cache miss (should never happen)
        if: steps.php-build-cache.outputs.cache-hit != 'true'
        run: exit 1

      - name: Install cached PHP's dependencies
        if: steps.php-build-cache.outputs.cache-hit == 'true'
        run: chmod +x ./bin/php7/install-dependencies.sh && ./bin/php7/install-dependencies.sh

      - name: Prefix PHP to PATH
        run: echo "$(pwd)/bin/php7/bin" >> $GITHUB_PATH

      - name: Install Composer
        run: curl -sS https://getcomposer.org/installer | php

      - name: Restore Composer package cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/composer/files
            ~/.cache/composer/vcs
          key: "composer-v2-cache-${{ matrix.php }}-${{ hashFiles('./composer.lock') }}"
          restore-keys: |
            composer-v2-cache-

      - name: Install Composer dependencies
        run: php composer.phar install --prefer-dist --no-interaction

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit --bootstrap vendor/autoload.php --fail-on-warning tests/phpunit

  integration:
    name: Integration tests
    needs: build-php
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu-20.04]
        php: [7.3.27, 7.4.15]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Restore PHP build cache
        id: php-build-cache
        uses: actions/cache@v2
        with:
          path: "./bin"
          key: "php-build-generic-${{ matrix.php }}-${{ matrix.image }}-${{ hashFiles('./tests/gh-actions/build.sh') }}"

      - name: Kill build on PHP build cache miss (should never happen)
        if: steps.php-build-cache.outputs.cache-hit != 'true'
        run: exit 1

      - name: Install cached PHP's dependencies
        if: steps.php-build-cache.outputs.cache-hit == 'true'
        run: chmod +x ./bin/php7/install-dependencies.sh && ./bin/php7/install-dependencies.sh

      - name: Prefix PHP to PATH
        run: echo "$(pwd)/bin/php7/bin" >> $GITHUB_PATH

      - name: Install Composer
        run: curl -sS https://getcomposer.org/installer | php

      - name: Restore Composer package cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/composer/files
            ~/.cache/composer/vcs
          key: "composer-v2-cache-${{ matrix.php }}-${{ hashFiles('./composer.lock') }}"
          restore-keys: |
            composer-v2-cache-

      - name: Install Composer dependencies
        run: php composer.phar install --no-dev --prefer-dist --no-interaction

      - name: Run integration tests
        run: ./tests/travis.sh -t4
